### ISSUE TITLE
Line termination error and additional libs

### ISSUE THREAD

**Issue by rogeriog** [yw-choi/qe_unfolding#1]
Not really an issue I suppose depending on the compiler and QE version it won't happen.
In line 171 I had to change to:
```
 wnk(ibnd-first_band+1, ik) = wnk(ibnd-first_band+1, ik) + sum(filter(1:npw) * dble(dconjg(evc(i1:i2,ibnd)) &
          *evc(i1:i2,ibnd)))

```
with continuation character otherwise an error was thrown. 
Later when compiling I had bunch of undefined references. Then I looked for all *.a files in my QE-6.8 compilation and I added these ones on Makefile QEOBJS to solve the problem:
`$(TOPDIR)/upflib/libupf.a    $(TOPDIR)/MBD/libmbd.a    $(TOPDIR)/XClib/xc_lib.a`

Maybe this helps someone else and may trigger changes for future version.

**Comment by yw-choi** [comment]
Great. Thanks a lot! I noticed your comment too late but I've made a commit that includes your suggestions. 8e1e08549bef4464ed1898ce22bc13ea2691f2e5
